---
# tasks file for slavecon
- name: "Installing docker-engine"
  yum:
    name: 
      - docker 
      - iproute-tc  
    state: present
   
- name: "Starting docker-engine"
  service:
    name: docker
    state: started
    enabled: yes

- name: "Copying daemon.json file content"
  copy:
    dest: /etc/docker/daemon.json
    content: |
            {
                "exec-opts": ["native.cgroupdriver=systemd"]
            }
  register: out

- name: "Restarting docker-engine"
  service:
    name: docker
    state: restarted
  when: out.changed == true

- name: "Adding Kubernetes repo"
  yum_repository:
    description: Yum for k8s
    name: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes
    exclude:
    - kubelet
    - kubeadm
    - kubectl

- name: "Installing kubeadm"
  yum:
    name: kubeadm
    disable_excludes: kubernetes

- name: "Enabling kubelet"
  service:
    name: kubelet
    state: started
    enabled: yes

- name: "Copying k8s.conf file"
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1
  register: out1

- name: "Reinitialting system controls"
  shell: "sysctl --system"
  when: out1.changed == true
