---
- hosts: master
  roles:
  - role: mastercon

- hosts: slave
  roles:
  - role: slavecon

- hosts: master
  tasks:
  - name: "Storing the join command"
    shell: "kubeadm token  create --print-join-command"
    register: join

  - set_fact:
      shared_variable: "{{ join.stdout }}"

  - add_host:
      name: "value"
      shared_variable: "{{ shared_variable }}"

- hosts: slave
  vars:
    join_link: "{{ hostvars['value']['shared_variable'] }}"
  tasks:
  - name: "Joining the master node"
    shell: "{{ join_link }}"

- hosts: master
  tasks:
  - name: Running Kube Flannel
    shell: kubectl apply -f /root/kube-flannel.yml

- hosts: master
  tasks:
  - name: "Copying the yaml file of infrastructure"
    copy:
      src: "cred.yml"
      dest: "/root/"
  - name: "Running the create command for creating the infrastructure" 
    shell: "kubectl create -f /root/cred.yml"



    
