---
# tasks file for k8s-master
- name: "Docker-engine and iproute-conf" 
  yum:
    name:
    - docker
    - iproute-tc
    state: present

- name: "Starting docker engine"
  service:
    name: docker
    state: started
    enabled: yes
   

- name: "Copying daemon.json file content"
  copy:
    dest: /etc/docker/daemon.json
    content: |
            {
                "exec-opts": ["native.cgroupdriver=systemd"]
            }
  register: out

- name: "Restarting docker-engine"
  service:
      name: docker
      state: restarted
  when: out.changed == true

- name: "Adding kubernetes repo"
  yum_repository:
    name: kubernetes
    description: Yum for k8s
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: 
    - kubelet 
    - kubeadm 
    - kubectl

- name: "Installing kubeadm"
  yum:
    name: kubeadm
    disable_excludes: kubernetes

- name: "Enabling kubelet"
  service:
    name: kubelet
    state: started
    enabled: yes

- name: "Pulling pods for master"
  shell: kubeadm config images pull
  changed_when: false

- name: "Copying k8s.conf file"
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1

- name: "Reinitiating system controls" 
  shell: "sysctl --system"
  changed_when: false

- name: "Initialising kubeadm"
  shell: "kubeadm init --pod-network-cidr={{ cidr }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"

- name: "Creating .kube file"
  file:
    path: $HOME/.kube
    state: directory

- name: "Copying file config file"
  copy:
    dest: $HOME/.kube/config
    src: /etc/kubernetes/admin.conf
    remote_src: yes

- name: "Copying flannel.yml file"
  template:
    dest: /root
    src: kube-flannel.yml


